name: boss-release
on:
  push:
    branches: [ main ]
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17.0
    - name: build
      run: |
        make dist && echo $(pwd)

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          _dist/*.zip
          _dist/*.tar.gz`
